import { expect, test } from '@playwright/test'

test('RTVI tool request requires a visible approval and Stop blocks further requests', async ({ page }) => {
  await page.goto('/e2e/astra-proof.html')
  const status = page.getByRole('region', { name: 'Voice tool controls' }).getByRole('status')
  await expect(status).toContainText('connected')
  await page.evaluate(() => dispatchEvent(new Event('proof-call')))
  await expect(page.getByText('Allow file_write for this call?')).toBeVisible()
  await expect(page.locator('pre')).toContainText('report.txt')
  await expect(page.locator('#executions')).toHaveText('0')
  await page.getByRole('button', { name: 'Allow this call' }).click()
  await expect(page.locator('#executions')).toHaveText('1')
  await page.evaluate(() => dispatchEvent(new Event('proof-call')))
  await expect(page.getByRole('button', { name: 'Deny', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stop voice tools' }).click()
  await expect(status).toContainText('stopped')
  await page.evaluate(() => dispatchEvent(new Event('proof-call')))
  await expect(page.locator('#executions')).toHaveText('1')
  await expect(page.getByRole('button', { name: 'Allow this call' })).toHaveCount(0)
})
