import { expect, test } from '@playwright/test'
test('explicit review survives reload and editing clears it', async ({ page }, testInfo) => {
  await page.goto('/e2e/memory-sensitive-proof.html')
  await page.getByRole('button', { name: 'Add Memory', exact: true }).click()
  await page.getByPlaceholder('What should I remember?').fill('Review proof')
  await page.getByPlaceholder('Details… (required)').fill('Synthetic review fact')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Source: manual', { exact: true })).toBeVisible()
  await expect(page.getByText('Not reviewed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Confirm reviewed' }).click()
  await expect(page.getByText(/^Reviewed:/)).toBeVisible()
  await page.reload()
  await expect(page.getByText(/^Reviewed:/)).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('memory-review.png') })
  await page.getByRole('button', { name: 'Edit entry' }).click()
  await page.locator('textarea').fill('Updated review fact')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Not reviewed', { exact: true })).toBeVisible()
})
