import { expect, test } from '@playwright/test'

test('conversation project selection controls saved memory and survives reload', async ({ page }, testInfo) => {
  await page.goto('/e2e/memory-sensitive-proof.html')
  await page.getByRole('button', { name: 'Create proof conversation' }).click()
  const project = page.getByLabel('Memory project ID for this conversation', { exact: false })
  await project.fill('project-a')
  await page.getByRole('button', { name: 'Add Memory', exact: true }).click()
  await page.getByPlaceholder('What should I remember?').fill('Private project note')
  await page.getByPlaceholder('Details… (required)').fill('Private Alpha content')
  await expect(page.getByLabel('Save in project project-a')).toBeChecked()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Preview AI memory context' }).click()
  await expect(page.locator('#result')).toContainText('Private Alpha content')
  await project.fill('project-b')
  await page.getByRole('button', { name: 'Save project assignment' }).click()
  await expect(page.getByRole('status')).toHaveText('Project assignment saved')
  await page.getByRole('button', { name: 'Preview AI memory context' }).click()
  await expect(page.locator('#result')).toHaveText('No eligible memories')
  await page.reload()
  await expect(project).toHaveValue('project-b')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('memory-project-mobile.png'), fullPage: true })
  await expect(page.getByText('Project: project-a', { exact: true })).toBeVisible()
  await project.fill('project-a')
  await page.getByRole('button', { name: 'Preview AI memory context' }).click()
  await expect(page.locator('#result')).toContainText('Private Alpha content')
})
